### ISSUE TITLE
about dialog

### ISSUE THREAD

**Issue by shonnon-zxs** [UCSB-AI/Aerial-Vision-and-Dialog-Navigation#1]
When drones run to different areas, should simulators or datasets have different dialog histories or content? But according to my understanding, in AVDN, from starting point a to b or c, will the drone yield the same question/dialog? And receive the same answer? Because in the task, the dialog content is not adjusted according to the position (but the time step T in the paper)

**Comment by UeFan** [comment]
Hi, 

If I understand your question correctly, you are asking the situation in the inference time. Lets say if the drone in the simulator at T=0 starts following some existing dialog history (commander instruction), and navigates to a new location that is not included in the dataset. So at this time, which should be T=1, there will be no following dialog available. The drone has to be moved back on the ground truth trajectory. 

This is a problem needed to be solved if someone wishes to train the follow agent in an online manner. However, keep in mind that the tasks proposed in the paper, such as ANDH task, use only the history dialogs as input. So in the task, the drone will be initialized at some starting locations that are included in the dataset. That means there are always dialog history ready and once the navigation action prediction finished (a stop action is output) the drone will be initialized to the next starting location.

**Comment by UeFan** [comment]
Hi, If I understand your question correctly, you are asking the situation in the inference time. Lets say if the drone in the simulator at T=0 starts following some existing dialog history (commander instruction), and navigates to a new location that is not included in the dataset. So at this time, which should be T=1, there will be no following dialog available. The drone has to be moved back on the ground truth trajectory. This is a problem needed to be solved if someone wishes to train the follow agent in an online manner. However, keep in mind that the tasks proposed in the paper, such as ANDH task, use only the history dialogs as input. So in the task, the drone will be initialized at some starting locations that are included in the dataset. That means there are always dialog history ready and once the navigation action prediction finished (a stop action is output) the drone will be initialized to the next starting location.On 24 May 2023, at 1:41 AM, shonnon-zxs ***@***.***> wrote:﻿
When drones run to different areas, should simulators or datasets have different dialog histories or content? But according to my understanding, in AVDN, from starting point a to b or c, will the drone yield the same question/dialog? And receive the same answer? Because in the task, the dialog content is not adjusted according to the position (but the time step T in the paper)

**Comment by shonnon-zxs** [comment]
OK, I have got it. This is consistent with my understanding.Thank you for your reply
