### ISSUE TITLE
Ended flag in teacher action

### ISSUE THREAD

**Issue by qiaogh97** [UCSB-AI/Aerial-Vision-and-Dialog-Navigation#11]
Dear authors,
      I see you set ended flag using 'np.array([0,0], dtype=np.float32)' in this code.
https://github.com/eric-ai-lab/Aerial-Vision-and-Dialog-Navigation/blob/cc095505846464de5179154fad0003ade05f1ac1/src/xview_et/agent.py#L420-L422
      However, when computing loss in line 665, this if will always be True since the ended data is numpy.array type and it will never be type(-100).
https://github.com/eric-ai-lab/Aerial-Vision-and-Dialog-Navigation/blob/cc095505846464de5179154fad0003ade05f1ac1/src/xview_et/agent.py#L662-L668

This situation may result in the calculation of losses for the data that have already been closed.

**Comment by UeFan** [comment]
Good catch! Thanks for letting us know. However, I think the comment here is not 100% correct, and only removing line 665 is fine (which keeps the training code the same as it it). The reason is that when teacher_action function determines the current view is reaching the final position, we can still choose to train the model's output to be [0,0] (which stands for no moving). 

Another option here is to replace line 665 with `if not ended[i]:`, which means if the navigation in this trajectory is ended, we do not train the model's output anymore. 

These two options are both reasonable to me. It needs some experiments to find out which one is better. I have pushed a fix here using the first option that I mentioned above because this will keep our baseline training unchanged.

**Comment by qiaogh97** [comment]
I think the second option is more common in VLN tasks, but the first option is also reasonable to me. I find some drones are always circling in place after arriving at their destination. Maybe training the model's output to be [0,0] will be the reason.

<img width="452" alt="image" src="https://github.com/eric-ai-lab/Aerial-Vision-and-Dialog-Navigation/assets/20733440/e290857e-2ee0-493b-b241-fec786f9fa7c">
